/**
 * OMG Phase 10 — Governance Change Management seed data.
 *
 * A representative change register spanning every category and every point of
 * the lifecycle, so the governance state machine and triggers have real
 * material to work against.
 */

import type {
  ChangeRequest,
  GovernanceTriggerRule,
  StateTransition,
} from '../types/changeManagement';

export const INITIAL_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'chg-1001',
    changeRef: 'CHG-0001',
    title: 'Upgrade fraud detection graph embedding model to v3.0',
    description:
      'Replace the v2.4 graph embedding model with v3.0, which adds temporal edge features and retrains on 18 months of additional transaction history.',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    assetType: 'Agent',
    assetRiskLevel: 'Critical',
    requestedBy: 'Sarah Jenkins',
    requestedByRole: 'SUPER_ADMIN',
    category: 'Model Change',
    businessJustification:
      'v2.4 false-positive rate has drifted to 4.1% against a 2.5% tolerance, driving avoidable customer friction and manual review cost.',
    requestedDate: '2026-07-14',
    submittedDate: '2026-07-16',
    status: 'Under Review',
    impact: {
      Ownership: 'No Impact',
      Risk: 'Critical Impact',
      Validation: 'Critical Impact',
      Evidence: 'High Impact',
      Policy: 'Medium Impact',
      Compliance: 'High Impact',
      Monitoring: 'High Impact',
    },
    impactScore: 84,
    magnitude: 'Critical',
    reassessment: 'Executive Approval Required',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-07-18', notes: 'Business case accepted; friction cost is material.' },
      { role: 'Reviewer', approver: 'Dr. Aris Thorne', decision: 'Approved', decidedAt: '2026-07-22', notes: 'Validation plan covers drift, fairness and adversarial cases.' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Pending' },
      { role: 'Compliance Officer', approver: 'Robert Vance', decision: 'Pending' },
      { role: 'Governance Lead', approver: 'David Chen', decision: 'Pending' },
      { role: 'Executive Approver', approver: 'Sarah Jenkins', decision: 'Pending' },
    ],
  },
  {
    id: 'chg-1002',
    changeRef: 'CHG-0002',
    title: 'Switch concierge copilot foundation model provider',
    description:
      'Migrate the customer concierge copilot from the incumbent hosted foundation model to an alternative enterprise-tier provider with EU data residency.',
    assetId: 'ast-103',
    assetName: 'Customer Concierge Copilot',
    assetType: 'Copilot',
    assetRiskLevel: 'Medium',
    requestedBy: 'Marcus Vance',
    requestedByRole: 'BUSINESS_OWNER',
    category: 'Vendor Change',
    businessJustification:
      'Incumbent vendor cannot contractually guarantee EU data residency ahead of the Q4 regulatory deadline.',
    requestedDate: '2026-07-20',
    submittedDate: '2026-07-21',
    status: 'Submitted',
    impact: {
      Ownership: 'Low Impact',
      Risk: 'High Impact',
      Validation: 'High Impact',
      Evidence: 'Medium Impact',
      Policy: 'High Impact',
      Compliance: 'Critical Impact',
      Monitoring: 'Medium Impact',
    },
    impactScore: 72,
    magnitude: 'Critical',
    reassessment: 'Executive Approval Required',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-07-21', notes: 'Raised by the asset owner; residency risk is unacceptable.' },
      { role: 'Reviewer', approver: 'Dr. Aris Thorne', decision: 'Pending' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Pending' },
      { role: 'Compliance Officer', approver: 'Robert Vance', decision: 'Pending' },
      { role: 'Governance Lead', approver: 'David Chen', decision: 'Pending' },
      { role: 'Executive Approver', approver: 'Sarah Jenkins', decision: 'Pending' },
    ],
  },
  {
    id: 'chg-1003',
    changeRef: 'CHG-0003',
    title: 'Extend AML retrieval corpus with sanctions bulletin feed',
    description:
      'Add a licensed third-party sanctions bulletin feed to the AML retrieval index, refreshed daily.',
    assetId: 'ast-104',
    assetName: 'AML Regulatory Intelligence RAG',
    assetType: 'RAG System',
    assetRiskLevel: 'High',
    requestedBy: 'David Chen',
    requestedByRole: 'GOVERNANCE_ADMIN',
    category: 'Data Change',
    businessJustification:
      'Analysts are manually cross-checking sanctions bulletins the assistant cannot see, adding roughly 40 minutes per escalated case.',
    requestedDate: '2026-06-28',
    submittedDate: '2026-06-30',
    decidedDate: '2026-07-09',
    status: 'Approved',
    impact: {
      Ownership: 'No Impact',
      Risk: 'Medium Impact',
      Validation: 'Medium Impact',
      Evidence: 'Medium Impact',
      Policy: 'High Impact',
      Compliance: 'High Impact',
      Monitoring: 'Low Impact',
    },
    impactScore: 55,
    magnitude: 'Major',
    reassessment: 'Full Governance Review',
    decisionRationale:
      'Approved subject to purpose-limitation review of the licensed feed and quarterly corpus attestation.',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-07-02', notes: 'Operational benefit is clear.' },
      { role: 'Reviewer', approver: 'Dr. Aris Thorne', decision: 'Approved', decidedAt: '2026-07-05', notes: 'Retrieval precision re-tested on the extended corpus.' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Approved', decidedAt: '2026-07-07', notes: 'No change to inherent risk tier.' },
      { role: 'Governance Lead', approver: 'David Chen', decision: 'Approved', decidedAt: '2026-07-09', notes: 'Conditional on quarterly corpus attestation.' },
    ],
  },
  {
    id: 'chg-1004',
    changeRef: 'CHG-0004',
    title: 'Revise credit adverse-action explanation prompt',
    description:
      'Update the explanation prompt so adverse credit decisions cite the top three contributing factors in plain language.',
    assetId: 'ast-102',
    assetName: 'Retail Credit Scoring Engine',
    assetType: 'Model',
    assetRiskLevel: 'High',
    requestedBy: 'Robert Vance',
    requestedByRole: 'AUDITOR',
    category: 'Prompt Change',
    businessJustification:
      'Internal audit found adverse-action notices insufficiently specific to satisfy explainability obligations.',
    requestedDate: '2026-07-25',
    submittedDate: '2026-07-26',
    status: 'Under Review',
    impact: {
      Ownership: 'No Impact',
      Risk: 'Medium Impact',
      Validation: 'High Impact',
      Evidence: 'Medium Impact',
      Policy: 'Medium Impact',
      Compliance: 'High Impact',
      Monitoring: 'Low Impact',
    },
    impactScore: 51,
    magnitude: 'Major',
    reassessment: 'Full Governance Review',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-07-27', notes: 'Supports the audit finding closure.' },
      { role: 'Reviewer', approver: 'Dr. Aris Thorne', decision: 'Pending' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Pending' },
      { role: 'Governance Lead', approver: 'David Chen', decision: 'Pending' },
    ],
  },
  {
    id: 'chg-1005',
    changeRef: 'CHG-0005',
    title: 'Apply revised human oversight policy threshold',
    description:
      'POL-RSK-002 revision lowers the autonomous action approval threshold for portfolio rebalancing from 5% to 2% of position value.',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    assetType: 'Multi-Agent System',
    assetRiskLevel: 'Critical',
    requestedBy: 'Elena Rostova',
    requestedByRole: 'RISK_OFFICER',
    category: 'Policy Change',
    businessJustification:
      'Follows the CHG governance review of the unapproved autonomous rebalancing incident recorded against this asset.',
    requestedDate: '2026-08-02',
    submittedDate: '2026-08-03',
    status: 'Submitted',
    impact: {
      Ownership: 'Low Impact',
      Risk: 'Critical Impact',
      Validation: 'Medium Impact',
      Evidence: 'High Impact',
      Policy: 'Critical Impact',
      Compliance: 'High Impact',
      Monitoring: 'High Impact',
    },
    impactScore: 88,
    magnitude: 'Critical',
    reassessment: 'Executive Approval Required',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Pending' },
      { role: 'Reviewer', approver: 'Dr. Aris Thorne', decision: 'Pending' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Approved', decidedAt: '2026-08-03', notes: 'Raised by Model Risk following the incident review.' },
      { role: 'Compliance Officer', approver: 'Robert Vance', decision: 'Pending' },
      { role: 'Governance Lead', approver: 'David Chen', decision: 'Pending' },
      { role: 'Executive Approver', approver: 'Sarah Jenkins', decision: 'Pending' },
    ],
  },
  {
    id: 'chg-1006',
    changeRef: 'CHG-0006',
    title: 'Raise mortgage workflow latency alert threshold',
    description:
      'Increase the document intelligence latency alert threshold from 2s to 3.5s to suppress false alerts during nightly batch ingestion.',
    assetId: 'ast-105',
    assetName: 'Mortgage Document Intelligence Workflow',
    assetType: 'AI Workflow',
    assetRiskLevel: 'Medium',
    requestedBy: 'Sarah Jenkins',
    requestedByRole: 'SUPER_ADMIN',
    category: 'Operational Change',
    businessJustification:
      'Nightly batch ingestion generates roughly 30 false latency alerts per week, desensitising the on-call rota.',
    requestedDate: '2026-06-10',
    submittedDate: '2026-06-11',
    decidedDate: '2026-06-13',
    implementedDate: '2026-06-16',
    closedDate: '2026-06-20',
    status: 'Closed',
    impact: {
      Ownership: 'No Impact',
      Risk: 'Low Impact',
      Validation: 'No Impact',
      Evidence: 'No Impact',
      Policy: 'No Impact',
      Compliance: 'No Impact',
      Monitoring: 'Medium Impact',
    },
    impactScore: 14,
    magnitude: 'Minor',
    reassessment: 'No Reassessment',
    decisionRationale: 'Owner acknowledgement sufficient; no governance dimension materially affected.',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-06-13', notes: 'Threshold agreed with the on-call rota.' },
    ],
  },
  {
    id: 'chg-1007',
    changeRef: 'CHG-0007',
    title: 'Introduce open-source embedding model for document classification',
    description:
      'Replace the licensed embedding model in the mortgage workflow with a self-hosted open-weight alternative.',
    assetId: 'ast-105',
    assetName: 'Mortgage Document Intelligence Workflow',
    assetType: 'AI Workflow',
    assetRiskLevel: 'Medium',
    requestedBy: 'Dr. Aris Thorne',
    requestedByRole: 'VALIDATOR',
    category: 'Model Change',
    businessJustification:
      'Licence renewal is a six-figure annual cost for capability now matched by open-weight alternatives.',
    requestedDate: '2026-05-12',
    submittedDate: '2026-05-14',
    decidedDate: '2026-05-29',
    status: 'Rejected',
    impact: {
      Ownership: 'No Impact',
      Risk: 'High Impact',
      Validation: 'High Impact',
      Evidence: 'Medium Impact',
      Policy: 'Medium Impact',
      Compliance: 'Medium Impact',
      Monitoring: 'Medium Impact',
    },
    impactScore: 53,
    magnitude: 'Major',
    reassessment: 'Full Governance Review',
    decisionRationale:
      'Rejected: model supply chain provenance could not be evidenced to the standard POL-SEC-002 will require.',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-05-18', notes: 'Cost saving is attractive.' },
      { role: 'Reviewer', approver: 'Dr. Aris Thorne', decision: 'Approved', decidedAt: '2026-05-22', notes: 'Benchmarks within tolerance.' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Rejected', decidedAt: '2026-05-29', notes: 'Weight provenance unverifiable; supply chain integrity cannot be attested.' },
      { role: 'Governance Lead', approver: 'David Chen', decision: 'Pending' },
    ],
  },
  {
    id: 'chg-1008',
    changeRef: 'CHG-0008',
    title: 'Add real-time drift monitoring to credit scoring engine',
    description:
      'Instrument the credit scoring engine with population stability index monitoring and weekly drift reporting.',
    assetId: 'ast-102',
    assetName: 'Retail Credit Scoring Engine',
    assetType: 'Model',
    assetRiskLevel: 'High',
    requestedBy: 'Elena Rostova',
    requestedByRole: 'RISK_OFFICER',
    category: 'Operational Change',
    businessJustification:
      'Model risk policy requires continuous drift surveillance for High risk customer-impacting models.',
    requestedDate: '2026-07-01',
    submittedDate: '2026-07-02',
    decidedDate: '2026-07-08',
    implementedDate: '2026-07-15',
    status: 'Implemented',
    impact: {
      Ownership: 'No Impact',
      Risk: 'Medium Impact',
      Validation: 'Low Impact',
      Evidence: 'Low Impact',
      Policy: 'No Impact',
      Compliance: 'Low Impact',
      Monitoring: 'High Impact',
    },
    impactScore: 31,
    magnitude: 'Moderate',
    reassessment: 'Risk Review Required',
    decisionRationale: 'Approved; strengthens the control environment with no change to model behaviour.',
    approvals: [
      { role: 'Asset Owner', approver: 'Marcus Vance', decision: 'Approved', decidedAt: '2026-07-04', notes: 'No customer-facing impact.' },
      { role: 'Risk Manager', approver: 'Elena Rostova', decision: 'Approved', decidedAt: '2026-07-08', notes: 'Satisfies the model risk surveillance requirement.' },
    ],
  },
  {
    id: 'chg-1009',
    changeRef: 'CHG-0009',
    title: 'Draft: consolidate agent reasoning traces into governance evidence',
    description:
      'Capture multi-agent reasoning traces as structured governance evidence rather than free-text operational logs.',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    assetType: 'Multi-Agent System',
    assetRiskLevel: 'Critical',
    requestedBy: 'David Chen',
    requestedByRole: 'GOVERNANCE_ADMIN',
    category: 'Prompt Change',
    businessJustification:
      'Examiners have asked how autonomous decisions are reconstructed; free-text traces are not defensible evidence.',
    requestedDate: '2026-08-05',
    status: 'Draft',
  },
];

export const INITIAL_STATE_TRANSITIONS: StateTransition[] = [
  {
    id: 'stt-seed-001',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    fromState: 'Monitoring',
    toState: 'Change Requested',
    changeId: 'chg-1001',
    changeRef: 'CHG-0001',
    actor: 'Sarah Jenkins',
    timestamp: '2026-07-16 09:42:11',
    reason: 'CHG-0001 submitted for governance evaluation.',
  },
  {
    id: 'stt-seed-002',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    fromState: 'Change Requested',
    toState: 'Impact Assessment',
    changeId: 'chg-1001',
    changeRef: 'CHG-0001',
    actor: 'David Chen',
    timestamp: '2026-07-17 11:05:38',
    reason: 'Critical magnitude classification routed to full executive chain.',
  },
  {
    id: 'stt-seed-003',
    assetId: 'ast-104',
    assetName: 'AML Regulatory Intelligence RAG',
    fromState: 'Monitoring',
    toState: 'Change Requested',
    changeId: 'chg-1003',
    changeRef: 'CHG-0003',
    actor: 'David Chen',
    timestamp: '2026-06-30 14:20:02',
    reason: 'CHG-0003 submitted for governance evaluation.',
  },
  {
    id: 'stt-seed-004',
    assetId: 'ast-104',
    assetName: 'AML Regulatory Intelligence RAG',
    fromState: 'Reassessment',
    toState: 'Reapproved',
    changeId: 'chg-1003',
    changeRef: 'CHG-0003',
    actor: 'David Chen',
    timestamp: '2026-07-09 16:48:55',
    reason: 'CHG-0003 reapproved subject to quarterly corpus attestation.',
  },
  {
    id: 'stt-seed-005',
    assetId: 'ast-105',
    assetName: 'Mortgage Document Intelligence Workflow',
    fromState: 'Reapproved',
    toState: 'Production',
    changeId: 'chg-1006',
    changeRef: 'CHG-0006',
    actor: 'Sarah Jenkins',
    timestamp: '2026-06-16 10:12:44',
    reason: 'CHG-0006 implemented into production.',
  },
  {
    id: 'stt-seed-006',
    assetId: 'ast-105',
    assetName: 'Mortgage Document Intelligence Workflow',
    fromState: 'Production',
    toState: 'Monitoring',
    changeId: 'chg-1006',
    changeRef: 'CHG-0006',
    actor: 'Sarah Jenkins',
    timestamp: '2026-06-20 09:30:17',
    reason: 'CHG-0006 closed; asset returned to continuous monitoring.',
  },
  {
    id: 'stt-seed-007',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    fromState: 'Monitoring',
    toState: 'Change Requested',
    changeId: 'chg-1005',
    changeRef: 'CHG-0005',
    actor: 'Elena Rostova',
    timestamp: '2026-08-03 08:15:29',
    reason: 'Policy revision requires reassessment of autonomous action thresholds.',
  },
];

export const INITIAL_TRIGGER_RULES: GovernanceTriggerRule[] = [
  {
    id: 'trg-001',
    condition: 'Vendor Changed',
    action: 'Create Review',
    description:
      'A vendor or provider switch automatically raises a governance review of the asset before the change may proceed.',
    categories: ['Vendor Change'],
    enabled: true,
  },
  {
    id: 'trg-002',
    condition: 'Policy Updated',
    action: 'Identify Affected Assets',
    description:
      'A policy revision fans out across policy mappings to identify every asset that inherits the obligation.',
    categories: ['Policy Change'],
    enabled: true,
  },
  {
    id: 'trg-003',
    condition: 'Critical Risk Increased',
    action: 'Executive Escalation',
    description:
      'Any change assessed as Critical impact on risk escalates directly to executive approval authority.',
    categories: ['Model Change', 'Vendor Change', 'Data Change', 'Policy Change'],
    enabled: true,
  },
  {
    id: 'trg-004',
    condition: 'Model Replaced',
    action: 'Require Revalidation',
    description:
      'Replacing or retraining a model invalidates prior validation evidence and requires an independent revalidation.',
    categories: ['Model Change'],
    enabled: true,
  },
  {
    id: 'trg-005',
    condition: 'New Data Source Introduced',
    action: 'Notify Compliance',
    description:
      'Introducing a new data source notifies Compliance to confirm purpose limitation and consent scope.',
    categories: ['Data Change'],
    enabled: true,
  },
  {
    id: 'trg-006',
    condition: 'Monitoring Control Changed',
    action: 'Require Evidence Refresh',
    description:
      'Adjusting monitoring or control thresholds requires the operational evidence pack to be refreshed.',
    categories: ['Operational Change', 'Prompt Change'],
    enabled: true,
  },
];
