import type { AIAsset, User, AuditLog } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@enterprise-bank.com',
    role: 'Super Admin',
    department: 'Enterprise AI & Architecture',
    status: 'Active',
    lastLogin: '2026-08-07 10:15',
    assignedAssetsCount: 4,
  },
  {
    id: 'usr-2',
    name: 'David Chen',
    email: 'david.chen@enterprise-bank.com',
    role: 'Governance Admin',
    department: 'AI Governance Office',
    status: 'Active',
    lastLogin: '2026-08-07 09:30',
    assignedAssetsCount: 6,
  },
  {
    id: 'usr-3',
    name: 'Elena Rostova',
    email: 'elena.rostova@enterprise-bank.com',
    role: 'Risk Officer',
    department: 'Model Risk Management',
    status: 'Active',
    lastLogin: '2026-08-06 16:45',
    assignedAssetsCount: 5,
  },
  {
    id: 'usr-4',
    name: 'Marcus Vance',
    email: 'marcus.vance@enterprise-bank.com',
    role: 'Business Owner',
    department: 'Retail Banking & Wealth',
    status: 'Active',
    lastLogin: '2026-08-07 08:20',
    assignedAssetsCount: 3,
  },
  {
    id: 'usr-5',
    name: 'Amara Patel',
    email: 'amara.patel@enterprise-bank.com',
    role: 'Governance Admin',
    department: 'Regulatory Compliance',
    status: 'Active',
    lastLogin: '2026-08-05 14:10',
    assignedAssetsCount: 4,
  },
  {
    id: 'usr-6',
    name: 'Robert Thorne',
    email: 'robert.thorne@enterprise-bank.com',
    role: 'Viewer',
    department: 'Internal Audit',
    status: 'Active',
    lastLogin: '2026-08-04 11:00',
    assignedAssetsCount: 0,
  },
];

export const INITIAL_ASSETS: AIAsset[] = [
  {
    id: 'ast-101',
    name: 'Fraud Detection Sentinel Agent',
    type: 'Agent',
    description: 'Autonomous agent monitoring real-time transactions for fraud anomalies using graph embeddings.',
    department: 'Cyber Security & Fraud',
    version: '2.4.0',
    status: 'Production',
    riskLevel: 'Critical',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
      approver: 'David Chen',
    },
    techStack: ['Python', 'PyTorch', 'Kafka', 'Neo4j'],
    dataSensitivity: 'PII/Sensitive',
    validationScore: 94,
    createdAt: '2026-01-15',
    updatedAt: '2026-08-02',
    lastReviewDate: '2026-07-20',
    decisionOutcome: 'GO',
    tags: ['Real-Time', 'Autonomous', 'High-Impact'],
  },
  {
    id: 'ast-102',
    name: 'Retail Credit Scoring Engine',
    type: 'Model',
    description: 'Machine learning model calculating credit risk scores for personal loan underwriting.',
    department: 'Retail Credit & Underwriting',
    version: '3.1.2',
    status: 'Validation',
    riskLevel: 'High',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
    },
    techStack: ['XGBoost', 'Scikit-Learn', 'FastAPI'],
    dataSensitivity: 'Confidential',
    validationScore: 88,
    createdAt: '2026-03-10',
    updatedAt: '2026-08-05',
    lastReviewDate: '2026-07-28',
    decisionOutcome: 'CONDITIONAL GO',
    tags: ['Credit', 'Regulated', 'Underwriting'],
  },
  {
    id: 'ast-103',
    name: 'Customer Concierge Copilot',
    type: 'Copilot',
    description: 'LLM-powered conversational assistant helping branch reps resolve customer inquiries.',
    department: 'Customer Operations',
    version: '1.2.0',
    status: 'Production',
    riskLevel: 'Medium',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
      approver: 'David Chen',
    },
    techStack: ['Azure OpenAI', 'LangChain', 'React'],
    dataSensitivity: 'Internal',
    validationScore: 91,
    createdAt: '2026-02-01',
    updatedAt: '2026-07-15',
    lastReviewDate: '2026-07-15',
    decisionOutcome: 'GO',
    tags: ['Customer Service', 'LLM', 'Copilot'],
  },
  {
    id: 'ast-104',
    name: 'AML Regulatory Intelligence RAG',
    type: 'RAG System',
    description: 'Retrieval-augmented generation system querying financial crime compliance regulations.',
    department: 'Financial Crime & AML',
    version: '1.0.4',
    status: 'Review',
    riskLevel: 'High',
    ownership: {
      businessOwner: 'Amara Patel',
      technicalOwner: 'David Chen',
      riskOwner: 'Elena Rostova',
    },
    techStack: ['Pinecone', 'LlamaIndex', 'GPT-4o'],
    dataSensitivity: 'Confidential',
    validationScore: 82,
    createdAt: '2026-05-12',
    updatedAt: '2026-08-06',
    lastReviewDate: '2026-08-01',
    decisionOutcome: 'PENDING',
    tags: ['AML', 'Compliance', 'RAG'],
  },
  {
    id: 'ast-105',
    name: 'Mortgage Document Intelligence Workflow',
    type: 'AI Workflow',
    description: 'Automated OCR & extraction pipeline parsing applicant income docs and tax returns.',
    department: 'Mortgage Services',
    version: '2.0.1',
    status: 'Production',
    riskLevel: 'Medium',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
      approver: 'David Chen',
    },
    techStack: ['AWS Textract', 'Python', 'Temporal'],
    dataSensitivity: 'PII/Sensitive',
    validationScore: 95,
    createdAt: '2026-02-20',
    updatedAt: '2026-06-30',
    lastReviewDate: '2026-06-30',
    decisionOutcome: 'GO',
    tags: ['Document AI', 'Workflow', 'Mortgage'],
  },
  {
    id: 'ast-106',
    name: 'Enterprise Portfolio Multi-Agent System',
    type: 'Multi-Agent System',
    description: 'Multi-agent orchestration swarm conducting automated stress testing & asset rebalancing.',
    department: 'Capital Markets & Wealth',
    version: '0.9.1',
    status: 'Draft',
    riskLevel: 'Critical',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
    },
    techStack: ['AutoGen', 'CrewAI', 'Python'],
    dataSensitivity: 'Restricted',
    validationScore: 65,
    createdAt: '2026-07-01',
    updatedAt: '2026-08-04',
    decisionOutcome: 'NO GO',
    tags: ['Trading', 'Multi-Agent', 'High-Risk'],
  },
  {
    id: 'ast-107',
    name: 'Salesforce Einstein AI Assistant',
    type: 'Third-Party AI Service',
    description: 'Third-party CRM AI capability predicting client churn and lead conversion scoring.',
    department: 'Global Sales',
    version: 'Enterprise 2026',
    status: 'Production',
    riskLevel: 'Low',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'David Chen',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
      approver: 'David Chen',
    },
    techStack: ['Salesforce Cloud'],
    dataSensitivity: 'Internal',
    validationScore: 98,
    createdAt: '2025-11-10',
    updatedAt: '2026-04-12',
    lastReviewDate: '2026-04-12',
    decisionOutcome: 'GO',
    tags: ['Third-Party', 'SaaS', 'CRM'],
  },
  {
    id: 'ast-108',
    name: 'Commercial Risk Analysis LLM',
    type: 'LLM',
    description: 'Fine-tuned domain LLM summarizing annual financial reports for commercial credit officers.',
    department: 'Commercial Banking',
    version: '1.5.0',
    status: 'Approval',
    riskLevel: 'High',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
    },
    techStack: ['Mistral-7B-Instruct', 'vLLM', 'Ray'],
    dataSensitivity: 'Confidential',
    validationScore: 89,
    createdAt: '2026-04-05',
    updatedAt: '2026-08-03',
    lastReviewDate: '2026-07-29',
    decisionOutcome: 'CONDITIONAL GO',
    tags: ['LLM', 'Fine-Tuned', 'Commercial'],
  },
  {
    id: 'ast-109',
    name: 'HR Talent Matching Portal',
    type: 'Application',
    description: 'Internal Web App scoring internal candidate skill profiles against open reqs.',
    department: 'Human Resources',
    version: '1.1.0',
    status: 'Production',
    riskLevel: 'Low',
    ownership: {
      businessOwner: 'Amara Patel',
      technicalOwner: 'David Chen',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'Amara Patel',
      approver: 'David Chen',
    },
    techStack: ['React', 'Node.js', 'PostgreSQL'],
    dataSensitivity: 'Internal',
    validationScore: 92,
    createdAt: '2026-02-14',
    updatedAt: '2026-05-20',
    lastReviewDate: '2026-05-20',
    decisionOutcome: 'GO',
    tags: ['HR', 'Talent', 'Internal'],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1001',
    timestamp: '2026-08-07 10:42:15',
    userId: 'usr-2',
    userName: 'David Chen',
    userRole: 'Governance Admin',
    action: 'DECISION_EXECUTED',
    entityType: 'Decision',
    entityId: 'ast-101',
    entityName: 'Fraud Detection Sentinel Agent',
    details: 'Executed Decision: GO for Fraud Detection Sentinel Agent (v2.4.0) after human override verification.',
    ipAddress: '10.240.12.88',
  },
  {
    id: 'log-1002',
    timestamp: '2026-08-06 16:20:04',
    userId: 'usr-3',
    userName: 'Elena Rostova',
    userRole: 'Risk Officer',
    action: 'RISK_ASSESSMENT_COMPLETED',
    entityType: 'Risk',
    entityId: 'ast-106',
    entityName: 'Enterprise Portfolio Multi-Agent System',
    details: 'Completed Risk Assessment wizard. Classified risk tier as CRITICAL due to unmonitored trade execution authority.',
    ipAddress: '10.240.14.12',
  },
  {
    id: 'log-1003',
    timestamp: '2026-08-05 14:15:30',
    userId: 'usr-1',
    userName: 'Sarah Jenkins',
    userRole: 'Super Admin',
    action: 'OWNERSHIP_UPDATED',
    entityType: 'Ownership',
    entityId: 'ast-102',
    entityName: 'Retail Credit Scoring Engine',
    details: 'Assigned Compliance Owner: Amara Patel and Technical Owner: Sarah Jenkins.',
    ipAddress: '10.240.10.05',
  },
  {
    id: 'log-1004',
    timestamp: '2026-08-04 11:30:12',
    userId: 'usr-2',
    userName: 'David Chen',
    userRole: 'Governance Admin',
    action: 'ASSET_CREATED',
    entityType: 'Asset',
    entityId: 'ast-106',
    entityName: 'Enterprise Portfolio Multi-Agent System',
    details: 'Registered new AI Asset type: Multi-Agent System under Capital Markets & Wealth department.',
    ipAddress: '10.240.12.88',
  },
];
