import type { 
  AIAsset, 
  User, 
  AuditLog, 
  PersonaDemoUser, 
  ValidationRecord, 
  EvidenceDocument, 
  Finding 
} from '../types';

export const DEMO_PERSONAS: PersonaDemoUser[] = [
  {
    role: 'SUPER_ADMIN',
    title: 'Super Admin',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@enterprise-bank.com',
    department: 'Enterprise AI & Architecture',
    description: 'Platform Owner • Full system access, user management, platform settings & governance config.',
    icon: '👑',
    allowedNav: [
      '/', '/dashboard', '/assets', '/ownership', '/risk', 
      '/validation', '/evidence', '/review-workbench', '/findings', '/validation-dashboard', 
      '/decision-intelligence', '/governance-blockers', '/decision-workbench-v4', '/decision-dashboard',
      '/decision-governance', '/users', '/audit-logs'
    ],
  },
  {
    role: 'GOVERNANCE_ADMIN',
    title: 'Governance Admin',
    name: 'David Chen',
    email: 'david.chen@enterprise-bank.com',
    department: 'AI Governance Office',
    description: 'Program Manager • Manage AI Assets, Validations, Evidence & Decision Intelligence.',
    icon: '🛡️',
    allowedNav: [
      '/', '/dashboard', '/assets', '/ownership', '/risk', 
      '/validation', '/evidence', '/review-workbench', '/findings', '/validation-dashboard', 
      '/decision-intelligence', '/governance-blockers', '/decision-workbench-v4', '/decision-dashboard',
      '/decision-governance', '/audit-logs'
    ],
  },
  {
    role: 'RISK_OFFICER',
    title: 'Risk Officer',
    name: 'Elena Rostova',
    email: 'elena.rostova@enterprise-bank.com',
    department: 'Model Risk Management',
    description: 'Risk Governance • Perform Risk Assessment Wizard, Risk Evidence Reviews & Blockers.',
    icon: '⚡',
    allowedNav: [
      '/', '/dashboard', '/assets', '/risk', '/evidence', '/review-workbench', '/findings', 
      '/decision-intelligence', '/governance-blockers', '/decision-dashboard', '/audit-logs'
    ],
  },
  {
    role: 'BUSINESS_OWNER',
    title: 'Business Owner',
    name: 'Marcus Vance',
    email: 'marcus.vance@enterprise-bank.com',
    department: 'Retail Banking & Wealth',
    description: 'Business Accountability • Create assets, submit evidence, manage assigned assets.',
    icon: '💼',
    allowedNav: ['/', '/dashboard', '/assets', '/ownership', '/evidence', '/decision-intelligence'],
  },
  {
    role: 'VALIDATOR',
    title: 'Validator',
    name: 'Dr. Aris Thorne',
    email: 'aris.thorne@enterprise-bank.com',
    department: 'AI Validation & Testing Center',
    description: 'Validation Officer • Model validation reviews, test evidence submission & scorecards.',
    icon: '🧪',
    allowedNav: [
      '/', '/dashboard', '/assets', '/validation', '/evidence', '/review-workbench', '/findings', 
      '/validation-dashboard', '/decision-intelligence'
    ],
  },
  {
    role: 'AUDITOR',
    title: 'Auditor',
    name: 'Robert Vance',
    email: 'robert.vance@enterprise-bank.com',
    department: 'Internal Audit & Compliance',
    description: 'Independent Auditor • Read-only audit logs, evidence review & compliance verification.',
    icon: '📜',
    allowedNav: ['/', '/dashboard', '/assets', '/evidence', '/findings', '/decision-dashboard', '/audit-logs'],
  },
  {
    role: 'VIEWER',
    title: 'Viewer',
    name: 'Claire Sterling',
    email: 'claire.sterling@enterprise-bank.com',
    department: 'Executive Board Observer',
    description: 'Executive Viewer • Executive Dashboard visibility & read-only reporting.',
    icon: '👁️',
    allowedNav: ['/', '/dashboard', '/assets', '/validation-dashboard', '/decision-dashboard'],
  },
];

export const INITIAL_USERS: User[] = DEMO_PERSONAS.map((p, idx) => ({
  id: `usr-${idx + 1}`,
  name: p.name,
  email: p.email,
  role: p.role,
  department: p.department,
  status: 'Active',
  lastLogin: '2026-08-07 10:15',
  assignedAssetsCount: (idx % 3) + 2,
}));

export const INITIAL_ASSETS: AIAsset[] = [
  {
    id: 'ast-101',
    name: 'Fraud Detection Sentinel Agent',
    type: 'Agent',
    description: 'Autonomous agent monitoring real-time transactions for fraud anomalies using graph embeddings.',
    department: 'Cyber Security & Fraud',
    version: '2.4.0',
    status: 'Production',
    riskLevel: 'Critical',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'David Chen',
      approver: 'David Chen',
    },
    techStack: ['Python', 'PyTorch', 'Kafka', 'Neo4j'],
    dataSensitivity: 'PII/Sensitive',
    validationScore: 94,
    createdAt: '2026-01-15',
    updatedAt: '2026-08-02',
    lastReviewDate: '2026-07-20',
    decisionOutcome: 'GO',
    tags: ['Real-Time', 'Autonomous', 'High-Impact'],
  },
  {
    id: 'ast-102',
    name: 'Retail Credit Scoring Engine',
    type: 'Model',
    description: 'Machine learning model calculating credit risk scores for personal loan underwriting.',
    department: 'Retail Credit & Underwriting',
    version: '3.1.2',
    status: 'Validation',
    riskLevel: 'High',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'David Chen',
    },
    techStack: ['XGBoost', 'Scikit-Learn', 'FastAPI'],
    dataSensitivity: 'Confidential',
    validationScore: 88,
    createdAt: '2026-03-10',
    updatedAt: '2026-08-05',
    lastReviewDate: '2026-07-28',
    decisionOutcome: 'CONDITIONAL GO',
    tags: ['Credit', 'Regulated', 'Underwriting'],
  },
  {
    id: 'ast-103',
    name: 'Customer Concierge Copilot',
    type: 'Copilot',
    description: 'LLM-powered conversational assistant helping branch reps resolve customer inquiries.',
    department: 'Customer Operations',
    version: '1.2.0',
    status: 'Production',
    riskLevel: 'Medium',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'David Chen',
      approver: 'David Chen',
    },
    techStack: ['Azure OpenAI', 'LangChain', 'React'],
    dataSensitivity: 'Internal',
    validationScore: 91,
    createdAt: '2026-02-01',
    updatedAt: '2026-07-15',
    lastReviewDate: '2026-07-15',
    decisionOutcome: 'GO',
    tags: ['Customer Service', 'LLM', 'Copilot'],
  },
  {
    id: 'ast-104',
    name: 'AML Regulatory Intelligence RAG',
    type: 'RAG System',
    description: 'Retrieval-augmented generation system querying financial crime compliance regulations.',
    department: 'Financial Crime & AML',
    version: '1.0.4',
    status: 'Review',
    riskLevel: 'High',
    ownership: {
      businessOwner: 'David Chen',
      technicalOwner: 'David Chen',
      riskOwner: 'Elena Rostova',
    },
    techStack: ['Pinecone', 'LlamaIndex', 'GPT-4o'],
    dataSensitivity: 'Confidential',
    validationScore: 82,
    createdAt: '2026-05-12',
    updatedAt: '2026-08-06',
    lastReviewDate: '2026-08-01',
    decisionOutcome: 'PENDING',
    tags: ['AML', 'Compliance', 'RAG'],
  },
  {
    id: 'ast-105',
    name: 'Mortgage Document Intelligence Workflow',
    type: 'AI Workflow',
    description: 'Automated OCR & extraction pipeline parsing applicant income docs and tax returns.',
    department: 'Mortgage Services',
    version: '2.0.1',
    status: 'Production',
    riskLevel: 'Medium',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
      riskOwner: 'Elena Rostova',
      complianceOwner: 'David Chen',
      approver: 'David Chen',
    },
    techStack: ['AWS Textract', 'Python', 'Temporal'],
    dataSensitivity: 'PII/Sensitive',
    validationScore: 95,
    createdAt: '2026-02-20',
    updatedAt: '2026-06-30',
    lastReviewDate: '2026-06-30',
    decisionOutcome: 'GO',
    tags: ['Document AI', 'Workflow', 'Mortgage'],
  },
  {
    id: 'ast-106',
    name: 'Enterprise Portfolio Multi-Agent System',
    type: 'Multi-Agent System',
    description: 'Multi-agent orchestration swarm conducting automated stress testing & asset rebalancing.',
    department: 'Capital Markets & Wealth',
    version: '0.9.1',
    status: 'Draft',
    riskLevel: 'Critical',
    ownership: {
      businessOwner: 'Marcus Vance',
      technicalOwner: 'Sarah Jenkins',
    },
    techStack: ['AutoGen', 'CrewAI', 'Python'],
    dataSensitivity: 'Restricted',
    validationScore: 65,
    createdAt: '2026-07-01',
    updatedAt: '2026-08-04',
    decisionOutcome: 'NO GO',
    tags: ['Trading', 'Multi-Agent', 'High-Risk'],
  },
];

export const INITIAL_VALIDATIONS: ValidationRecord[] = [
  {
    id: 'val-201',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    category: 'Security',
    reviewer: 'Dr. Aris Thorne',
    reviewerRole: 'VALIDATOR',
    reviewDate: '2026-08-02',
    status: 'Approved',
    score: 100,
    findings: 'Penetration test passed with zero critical vulnerabilities. API secret key rotation verified.',
    recommendations: 'Enable automated daily key rotation in HashiCorp Vault.',
    evidenceRefs: ['evd-301', 'evd-302'],
  },
  {
    id: 'val-202',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    category: 'Model',
    reviewer: 'Elena Rostova',
    reviewerRole: 'RISK_OFFICER',
    reviewDate: '2026-08-03',
    status: 'Approved',
    score: 100,
    findings: 'Model bias audit completed across demographic segments. Precision rate 96.4%, Recall 94.2%.',
    recommendations: 'Maintain monthly drift monitoring on graph embeddings.',
    evidenceRefs: ['evd-303'],
  },
  {
    id: 'val-203',
    assetId: 'ast-102',
    assetName: 'Retail Credit Scoring Engine',
    category: 'Compliance',
    reviewer: 'David Chen',
    reviewerRole: 'GOVERNANCE_ADMIN',
    reviewDate: '2026-08-04',
    status: 'Approved',
    score: 100,
    findings: 'Fair Lending compliance assessment verified adverse action explanation generation.',
    recommendations: 'Re-validate decision tree explainability quarterly.',
    evidenceRefs: ['evd-304'],
  },
  {
    id: 'val-204',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    category: 'Technical',
    reviewer: 'Dr. Aris Thorne',
    reviewerRole: 'VALIDATOR',
    reviewDate: '2026-08-05',
    status: 'Rejected',
    score: 0,
    findings: 'Swarm agent loop failed emergency break-out test under market volatility simulation.',
    recommendations: 'Implement mandatory circuit-breaker pattern before re-submitting for validation.',
    evidenceRefs: ['evd-305'],
  },
];

export const INITIAL_EVIDENCE: EvidenceDocument[] = [
  {
    id: 'evd-301',
    title: 'Security Architecture & Penetration Test Report',
    category: 'Security Evidence',
    deliverableType: 'Security Review Document',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    uploadedBy: 'Sarah Jenkins',
    uploadDate: '2026-07-28',
    version: '2.0',
    status: 'Approved',
    description: 'Comprehensive security review, threat model, and 3rd party penetration test evidence for Sentinel Agent.',
  },
  {
    id: 'evd-302',
    title: 'Sentinel API Design & OAuth Authorization Specs',
    category: 'Technical Evidence',
    deliverableType: 'API Design Specification',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    uploadedBy: 'Sarah Jenkins',
    uploadDate: '2026-07-25',
    version: '1.4',
    status: 'Approved',
    description: 'REST API endpoints, JSON schemas, rate-limiting rules, and JWT auth flow specs.',
  },
  {
    id: 'evd-303',
    title: 'Model Fairness & Demographic Bias Audit Report',
    category: 'Model Evidence',
    deliverableType: 'Test Strategy & Evidence',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    uploadedBy: 'Elena Rostova',
    uploadDate: '2026-07-29',
    version: '1.0',
    status: 'Approved',
    description: 'Independent model risk management evaluation of disparate impact and false positive distribution.',
  },
  {
    id: 'evd-304',
    title: 'Retail Credit Scoring Functional Requirements Spec',
    category: 'Business Evidence',
    deliverableType: 'Functional Requirements Specification',
    assetId: 'ast-102',
    assetName: 'Retail Credit Scoring Engine',
    uploadedBy: 'Marcus Vance',
    uploadDate: '2026-07-10',
    version: '3.1',
    status: 'Approved',
    description: 'Underwriting rules, adverse action notification logic, and credit tier boundaries.',
  },
  {
    id: 'evd-305',
    title: 'Multi-Agent Stress Testing & Volatility Simulation Logs',
    category: 'Technical Evidence',
    deliverableType: 'Test Strategy & Evidence',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    uploadedBy: 'Dr. Aris Thorne',
    uploadDate: '2026-08-04',
    version: '0.9',
    status: 'Rejected',
    description: 'Simulation run output revealing deadlocks during agent consensus on flash crash scenario.',
  },
];

export const INITIAL_FINDINGS: Finding[] = [
  {
    id: 'fnd-401',
    title: 'Agent Consensus Circuit Breaker Missing',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    severity: 'Critical',
    status: 'Open',
    assignedTo: 'Sarah Jenkins',
    reportedBy: 'Dr. Aris Thorne',
    reportedDate: '2026-08-05',
    description: 'Multi-agent swarm lacks hard-coded execution kill switch if market volatility exceeds 15% threshold within 60 seconds.',
  },
  {
    id: 'fnd-402',
    title: 'Vault Key Rotation Automation Unverified',
    assetId: 'ast-101',
    assetName: 'Fraud Detection Sentinel Agent',
    severity: 'Low',
    status: 'In Progress',
    assignedTo: 'Sarah Jenkins',
    reportedBy: 'Dr. Aris Thorne',
    reportedDate: '2026-08-02',
    description: 'Daily key rotation cron job configuration needs automated health check probe.',
    resolutionNotes: 'Configuring Kubernetes CronJob probe.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1001',
    timestamp: '2026-08-07 10:42:15',
    userId: 'usr-2',
    userName: 'David Chen',
    userRole: 'GOVERNANCE_ADMIN',
    action: 'DECISION_EXECUTED',
    entityType: 'Decision',
    entityId: 'ast-101',
    entityName: 'Fraud Detection Sentinel Agent',
    details: 'Executed Decision: GO for Fraud Detection Sentinel Agent (v2.4.0) after human override verification.',
    ipAddress: '10.240.12.88',
  },
];
