/**
 * OMG Phase 9 — Policy Governance seed data.
 *
 * Kept separate from mockData.ts because policy governance is its own domain:
 * OMG moves from governing assets to governing the rules that bind them.
 */

import type { Policy, PolicyMapping, PolicyViolation } from '../types';

export const INITIAL_POLICIES: Policy[] = [
  {
    id: 'pol-001',
    policyRef: 'POL-GOV-001',
    name: 'Named Accountable Ownership Required',
    category: 'Governance Policies',
    owner: 'David Chen',
    ownerRole: 'Governance Admin',
    effectiveDate: '2025-01-01',
    reviewDate: '2026-12-31',
    status: 'Active',
    description:
      'Every AI asset must carry a named Business, Technical, Risk and Compliance Owner plus a designated Approver before it may progress beyond registration.',
    mandatory: true,
    enforcementRule: 'REQUIRE_FULL_OWNERSHIP',
  },
  {
    id: 'pol-002',
    policyRef: 'POL-GOV-002',
    name: 'Decision Authority Before Production',
    category: 'Governance Policies',
    owner: 'Sarah Jenkins',
    ownerRole: 'Super Admin',
    effectiveDate: '2025-01-01',
    reviewDate: '2026-10-31',
    status: 'Active',
    description:
      'No AI asset may operate in production without a recorded GO or CONDITIONAL GO decision from an authorised decision owner.',
    mandatory: true,
    enforcementRule: 'REQUIRE_DECISION_BEFORE_PRODUCTION',
  },
  {
    id: 'pol-003',
    policyRef: 'POL-RSK-001',
    name: 'Independent Validation For High Risk AI',
    category: 'Risk Policies',
    owner: 'Elena Rostova',
    ownerRole: 'Risk Officer',
    effectiveDate: '2025-02-15',
    reviewDate: '2026-09-30',
    status: 'Active',
    description:
      'High and Critical risk AI assets require an approved independent validation review before production deployment.',
    mandatory: true,
    enforcementRule: 'REQUIRE_VALIDATION_FOR_HIGH_RISK',
  },
  {
    id: 'pol-004',
    policyRef: 'POL-RSK-002',
    name: 'Human Oversight Required',
    category: 'Risk Policies',
    owner: 'Elena Rostova',
    ownerRole: 'Risk Officer',
    effectiveDate: '2025-02-15',
    reviewDate: '2026-08-31',
    status: 'Active',
    description:
      'High and Critical risk autonomous AI must enforce human-in-the-loop or human-on-the-loop override authority with a documented kill switch protocol.',
    mandatory: true,
    enforcementRule: 'REQUIRE_HUMAN_OVERSIGHT_HIGH_RISK',
  },
  {
    id: 'pol-005',
    policyRef: 'POL-GOV-003',
    name: 'Governance Evidence Completeness',
    category: 'Governance Policies',
    owner: 'David Chen',
    ownerRole: 'Governance Admin',
    effectiveDate: '2025-03-01',
    reviewDate: '2026-11-30',
    status: 'Active',
    description:
      'Production AI assets must maintain a complete ODF governance evidence pack sufficient to satisfy an unannounced regulatory examination.',
    mandatory: true,
    enforcementRule: 'REQUIRE_EVIDENCE_FOR_PRODUCTION',
  },
  {
    id: 'pol-006',
    policyRef: 'POL-GOV-004',
    name: 'Periodic Governance Review Cadence',
    category: 'Governance Policies',
    owner: 'David Chen',
    ownerRole: 'Governance Admin',
    effectiveDate: '2025-03-01',
    reviewDate: '2026-12-31',
    status: 'Active',
    description:
      'High and Critical risk assets require quarterly governance review; all other assets require annual review. Overdue reviews constitute a policy breach.',
    mandatory: true,
    enforcementRule: 'REQUIRE_PERIODIC_REVIEW',
  },
  {
    id: 'pol-007',
    policyRef: 'POL-SEC-001',
    name: 'AI Data Protection & PII Safeguards',
    category: 'Security Policies',
    owner: 'Sarah Jenkins',
    ownerRole: 'Super Admin',
    effectiveDate: '2025-01-15',
    reviewDate: '2026-07-31',
    status: 'Active',
    description:
      'AI systems processing PII or Restricted data must enforce encryption in transit and at rest, with access mediated by least-privilege controls.',
    mandatory: true,
  },
  {
    id: 'pol-008',
    policyRef: 'POL-SEC-002',
    name: 'Model Supply Chain Integrity',
    category: 'Security Policies',
    owner: 'Sarah Jenkins',
    ownerRole: 'Super Admin',
    effectiveDate: '2025-06-01',
    reviewDate: '2027-05-31',
    status: 'Under Review',
    description:
      'Foundation models, weights and inference dependencies must originate from approved registries with provenance recorded in the asset registry.',
    mandatory: false,
  },
  {
    id: 'pol-009',
    policyRef: 'POL-PRV-001',
    name: 'Algorithmic Fairness & Bias Audit',
    category: 'Privacy Policies',
    owner: 'Robert Vance',
    ownerRole: 'Auditor',
    effectiveDate: '2025-04-01',
    reviewDate: '2026-09-30',
    status: 'Active',
    description:
      'Customer-impacting AI models must undergo demographic disparate impact testing and maintain an explainability record for adverse decisions.',
    mandatory: false,
  },
  {
    id: 'pol-010',
    policyRef: 'POL-PRV-002',
    name: 'Purpose Limitation For Customer Data',
    category: 'Privacy Policies',
    owner: 'Robert Vance',
    ownerRole: 'Auditor',
    effectiveDate: '2025-04-01',
    reviewDate: '2026-10-31',
    status: 'Active',
    description:
      'Customer data used for AI training or retrieval must remain within the purpose for which consent was obtained, with lineage recorded.',
    mandatory: true,
  },
  {
    id: 'pol-011',
    policyRef: 'POL-VND-001',
    name: 'Third-Party AI Vendor Assurance',
    category: 'Vendor Policies',
    owner: 'Marcus Vance',
    ownerRole: 'Business Owner',
    effectiveDate: '2025-05-01',
    reviewDate: '2026-11-30',
    status: 'Active',
    description:
      'External AI services must complete vendor security review, data residency confirmation and contractual model-change notification before integration.',
    mandatory: true,
    enforcementRule: 'REQUIRE_VENDOR_REVIEW',
  },
  {
    id: 'pol-012',
    policyRef: 'POL-VND-002',
    name: 'Vendor Model Change Notification',
    category: 'Vendor Policies',
    owner: 'Marcus Vance',
    ownerRole: 'Business Owner',
    effectiveDate: '2025-09-01',
    reviewDate: '2027-08-31',
    status: 'Draft',
    description:
      'Vendors must notify the enterprise of material model, prompt or guardrail changes at least 30 days before deployment into a governed workflow.',
    mandatory: false,
  },
];

export const INITIAL_POLICY_MAPPINGS: PolicyMapping[] = [
  {
    id: 'pmap-001',
    policyId: 'pol-004',
    policyName: 'Human Oversight Required',
    targetType: 'AI Asset',
    targetId: 'ast-101',
    targetName: 'Fraud Detection Sentinel Agent',
    mappedBy: 'Elena Rostova',
    mappedDate: '2025-03-12',
    notes: 'Autonomous transaction blocking requires human-on-the-loop review of blocked accounts.',
  },
  {
    id: 'pmap-002',
    policyId: 'pol-004',
    policyName: 'Human Oversight Required',
    targetType: 'AI Asset',
    targetId: 'ast-106',
    targetName: 'Enterprise Portfolio Multi-Agent System',
    mappedBy: 'Elena Rostova',
    mappedDate: '2025-06-02',
    notes: 'Multi-agent rebalancing must route above-threshold actions to a human approver.',
  },
  {
    id: 'pmap-003',
    policyId: 'pol-009',
    policyName: 'Algorithmic Fairness & Bias Audit',
    targetType: 'AI Asset',
    targetId: 'ast-102',
    targetName: 'Retail Credit Scoring Engine',
    mappedBy: 'Robert Vance',
    mappedDate: '2025-04-18',
    notes: 'Adverse credit decisions require documented explainability and disparate impact testing.',
  },
  {
    id: 'pmap-004',
    policyId: 'pol-010',
    policyName: 'Purpose Limitation For Customer Data',
    targetType: 'Asset Type',
    targetId: 'RAG System',
    targetName: 'RAG System',
    mappedBy: 'David Chen',
    mappedDate: '2025-05-09',
    notes: 'Retrieval corpora must be scoped to consented data domains.',
  },
  {
    id: 'pmap-005',
    policyId: 'pol-011',
    policyName: 'Third-Party AI Vendor Assurance',
    targetType: 'Asset Type',
    targetId: 'Third-Party AI Service',
    targetName: 'Third-Party AI Service',
    mappedBy: 'Marcus Vance',
    mappedDate: '2025-05-20',
  },
  {
    id: 'pmap-006',
    policyId: 'pol-001',
    policyName: 'Named Accountable Ownership Required',
    targetType: 'Business Unit',
    targetId: 'Retail Credit & Underwriting',
    targetName: 'Retail Credit & Underwriting',
    mappedBy: 'David Chen',
    mappedDate: '2025-02-01',
  },
  {
    id: 'pmap-007',
    policyId: 'pol-007',
    policyName: 'AI Data Protection & PII Safeguards',
    targetType: 'Business Unit',
    targetId: 'Customer Operations',
    targetName: 'Customer Operations',
    mappedBy: 'Sarah Jenkins',
    mappedDate: '2025-02-10',
    notes: 'Concierge copilot handles customer identifiers in live sessions.',
  },
  {
    id: 'pmap-008',
    policyId: 'pol-003',
    policyName: 'Independent Validation For High Risk AI',
    targetType: 'AI Asset',
    targetId: 'ast-104',
    targetName: 'AML Regulatory Intelligence RAG',
    mappedBy: 'Elena Rostova',
    mappedDate: '2025-07-01',
  },
  {
    id: 'pmap-009',
    policyId: 'pol-011',
    policyName: 'Third-Party AI Vendor Assurance',
    targetType: 'Vendor',
    targetId: 'vendor-foundation-model-enterprise',
    targetName: 'Foundation Model Vendor (Enterprise Tier)',
    mappedBy: 'Marcus Vance',
    mappedDate: '2025-06-15',
    notes: 'Covers hosted foundation model inference used by the concierge copilot.',
  },
  {
    id: 'pmap-010',
    policyId: 'pol-006',
    policyName: 'Periodic Governance Review Cadence',
    targetType: 'Business Unit',
    targetId: 'Capital Markets & Wealth',
    targetName: 'Capital Markets & Wealth',
    mappedBy: 'David Chen',
    mappedDate: '2025-06-20',
  },
];

export const INITIAL_POLICY_VIOLATIONS: PolicyViolation[] = [
  {
    id: 'pv-001',
    policyId: 'pol-009',
    policyName: 'Algorithmic Fairness & Bias Audit',
    violationType: 'Missing Bias Audit Evidence',
    assetId: 'ast-102',
    assetName: 'Retail Credit Scoring Engine',
    severity: 'High',
    owner: 'Robert Vance',
    detectionDate: '2026-06-18',
    status: 'Under Review',
    description:
      'Disparate impact testing for the latest model version has not been filed. Prior audit evidence relates to a superseded model release.',
  },
  {
    id: 'pv-002',
    policyId: 'pol-007',
    policyName: 'AI Data Protection & PII Safeguards',
    violationType: 'Unmasked Identifiers In Session Logs',
    assetId: 'ast-103',
    assetName: 'Customer Concierge Copilot',
    severity: 'Medium',
    owner: 'Marcus Vance',
    detectionDate: '2026-07-02',
    status: 'Remediated',
    description:
      'Customer identifiers were retained in conversation transcripts beyond the masked-logging window.',
    remediationNotes:
      'Masking filter deployed to the transcript pipeline; historical logs purged and verified by Information Security.',
  },
  {
    id: 'pv-003',
    policyId: 'pol-011',
    policyName: 'Third-Party AI Vendor Assurance',
    violationType: 'Vendor Review Not Refreshed',
    assetId: 'ast-103',
    assetName: 'Customer Concierge Copilot',
    severity: 'Medium',
    owner: 'Marcus Vance',
    detectionDate: '2026-07-22',
    status: 'Open',
    description:
      'The hosted foundation model vendor assurance review has lapsed past its annual refresh date.',
  },
  {
    id: 'pv-004',
    policyId: 'pol-010',
    policyName: 'Purpose Limitation For Customer Data',
    violationType: 'Retrieval Corpus Scope Drift',
    assetId: 'ast-104',
    assetName: 'AML Regulatory Intelligence RAG',
    severity: 'High',
    owner: 'David Chen',
    detectionDate: '2026-07-28',
    status: 'Open',
    description:
      'Retrieval index was extended with customer correspondence not covered by the original consent scope.',
  },
  {
    id: 'pv-005',
    policyId: 'pol-004',
    policyName: 'Human Oversight Required',
    violationType: 'Autonomous Action Above Threshold',
    assetId: 'ast-106',
    assetName: 'Enterprise Portfolio Multi-Agent System',
    severity: 'Critical',
    owner: 'Elena Rostova',
    detectionDate: '2026-08-01',
    status: 'Open',
    description:
      'Agent executed a portfolio rebalancing action above the human approval threshold without routing to a designated approver.',
  },
  {
    id: 'pv-006',
    policyId: 'pol-007',
    policyName: 'AI Data Protection & PII Safeguards',
    violationType: 'Encryption Standard Deviation',
    assetId: 'ast-105',
    assetName: 'Mortgage Document Intelligence Workflow',
    severity: 'Low',
    owner: 'Sarah Jenkins',
    detectionDate: '2026-05-30',
    status: 'Closed',
    description:
      'Document staging bucket used a deprecated encryption profile for a period of nine days.',
    remediationNotes:
      'Bucket policy updated to the current standard; closure verified by Internal Audit.',
  },
];
